// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA2duWJbFIDHSo6nGlvxQPwH8SUUQASyw',
    appId: '1:827679133165:web:6a3e378ce46c51fb342be4',
    messagingSenderId: '827679133165',
    projectId: 'vartalaap-f8b3c',
    authDomain: 'vartalaap-f8b3c.firebaseapp.com',
    storageBucket: 'vartalaap-f8b3c.appspot.com',
    measurementId: 'G-N0FT65V0VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRG3V4ORMZpA0znnEm3lQOfCjExBoNNqg',
    appId: '1:827679133165:android:bdf7cad20b51b75b342be4',
    messagingSenderId: '827679133165',
    projectId: 'vartalaap-f8b3c',
    storageBucket: 'vartalaap-f8b3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX6Ju6bK6d08Ja3hgPuYZm4KiVlsKMzZ8',
    appId: '1:827679133165:ios:f5c3afbc4f6472e5342be4',
    messagingSenderId: '827679133165',
    projectId: 'vartalaap-f8b3c',
    storageBucket: 'vartalaap-f8b3c.appspot.com',
    iosBundleId: 'com.example.vartalaap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX6Ju6bK6d08Ja3hgPuYZm4KiVlsKMzZ8',
    appId: '1:827679133165:ios:f5c3afbc4f6472e5342be4',
    messagingSenderId: '827679133165',
    projectId: 'vartalaap-f8b3c',
    storageBucket: 'vartalaap-f8b3c.appspot.com',
    iosBundleId: 'com.example.vartalaap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA2duWJbFIDHSo6nGlvxQPwH8SUUQASyw',
    appId: '1:827679133165:web:33dc89959217b272342be4',
    messagingSenderId: '827679133165',
    projectId: 'vartalaap-f8b3c',
    authDomain: 'vartalaap-f8b3c.firebaseapp.com',
    storageBucket: 'vartalaap-f8b3c.appspot.com',
    measurementId: 'G-L6RB9XBE7E',
  );
}
